name: ❓ Question
description: Ask a question or start a discussion.
labels: "question"
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      options:
        - label: I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Desktop/issues?q=is%3Aissue)
          required: true
        - label: I agree to follow Scribe-Desktop's [Code of Conduct](https://github.com/scribe-org/Scribe-Desktop/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in Scribe!
