name: welcome

on: [issues] # pull_request

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "## Welcome!\nThanks so much for opening your first issue :) This bot's here to let you know we'll be with you as soon as we can.\n\nBest regards,\nThe Scribe Team"
          # pr-message: "## Thank you!\nWe appreciate your initiative in contributing to Scribe. This bot's here to say the obvious: we hope this is the first of many PRs to come :)\n\nAll the best,\nThe Scribe Team"
